language: python
jobs:
  include:
    - os: linux
      dist: trusty
      python: 3.8
      env: TOXENV=py38
    - os: linux
      dist: focal
      python: 3.8
      env: TOXENV=py38

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install cython
  - pip install coveralls
  - pip install pdb-profiling==0.2.7a9

# command to run tests
script:
  - coverage run --source=pdb_profiling -m pytest ./test/pytest/

after_success:
  - coveralls