language: python

python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip3 install cython
  - pip3 install coveralls

# command to run tests
script:
  - python3 setup.py build_ext --inplace
  - python3 setup.py install
  - coverage run --source=pdb_profiling -m pytest ./test/pytest/

after_success:
  - coveralls