language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
before_install:
  - python -m pip install cython
  - python -m pip install coveralls
install:
  - python setup.py build_ext --inplace
  - python setup.py install

# command to run tests
script:
  - coverage run --source=pdb_profiling -m pytest ./test/pytest/

after_success:
  - coveralls