language: python

python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - python3 -m pip install --upgrade pip
#  - pip install --upgrade pytest
#  - pip install coveralls
  - python3 -m pip install toml
#  - pip install pytest-cython
  - python3 -m pip install aiosqlite
  - python3 -m pip install $(python -c 'import toml;c = toml.load("pyproject.toml");print("\n".join(c["build-system"]["requires"]))')
  - python3 setup.py build_ext --inplace
  - python3 setup.py install

# command to run tests
script:
  - python3 -c 'from pdb_profiling import default_config;default_config();from pdb_profiling.cython.cyrange import to_interval;'
#  - pytest ./test/pytest/ --doctest-cython
#  - coverage run --source=pdb_profiling -m pytest ./test/pytest/ --doctest-cython

#after_success:
#  - coveralls