language: python

python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade pytest
  - python3 -m pip install coveralls
  - python3 -m pip install toml
  - python3 -m pip install pytest-cython
  - python3 -m pip install aiosqlite
  - python3 -m pip install sqlalchemy --upgrade
  - python3 -m pip install $(python -c 'import toml;c = toml.load("pyproject.toml");print("\n".join(c["build-system"]["requires"]))')
  - python3 setup.py build_ext --inplace
  - python3 setup.py install

# command to run tests
script:
  - coverage run --source=pdb_profiling -m pytest ./test/pytest/ --doctest-cython

after_success:
  - coveralls