language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install pdb-profiling==0.2.6b4
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=pdb_profiling -m pytest ./test/pytest/

after_success:
  - coveralls