language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install pdb-profiling
  - pip install coveralls

# command to run tests
script:
  - coverage run -m pytest ./test/pytest/

after_success:
  - coveralls